package com.sunrisekcdeveloper.medialion.features.mycollection

sealed interface MyCollectionsUIState
object FailedToFetchCollections : MyCollectionsUIState
object Loading : MyCollectionsUIState
object MyCollectionsContent : MyCollectionsUIState